### ISSUE TITLE
Persistent connection

### ISSUE THREAD

**Issue by cosmincatalin** [joezug/rustbricks#1]
Awesome package and initiative. Looking at the official Python package, I see it uses a persistent connection, which ultimately gives better performance in executing subsequent queries. Is this something that can be added here as well?

**Comment by joezug** [comment]
hey, thanks for the kind words and for checking out the package. i just released 0.1.0, you'll find a new `DatabricksSession` struct that handles session-based interactions with the api, keeping the connection alive for better performance on subsequent queries. hope you find it works well and boosts your projects. let me know how it goes or if you run into any issues. cheers!

**Comment by cosmincatalin** [comment]
I've compared performance between the official Python package and this one, and sadly Python wins. I believe it has to do with the fact that in the case of the Python package, the persistent connection is made to the Thrift server and not simply an http session.
